version: '3'
services:
  db:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mydb
      - MYSQL_HOST=localhost
#      - MYSQL_INITDB=/docker-entrypoint-initdb.d/db_connector.py
#    volumes:
#      - C:\Users\osame\mysql:/var/lib/mysql:/docker-entrypoint-initdb.d
#    volumes:
#      - C:\Users\osame\mysql:/var/lib/mysql
#      - ./mysql:/var/lib/mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3309:3306"
#    expose:
#      - 3306

  rest_app:
    build: .
    container_name: restApp
    command: python rest_app.py
#    command: sh -c "/wait" && python rest_app.py
#    environment:
#      - WAIT_HOSTS=db:3306
#      - WAIT_HOSTS_TIMEOUT=300
#      - WAIT_SLEEP_INTERVAL=30
#      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - "5000:5000"
    expose:
      - 5000
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - "db"

  backend_testing_app:
    build:
      context: ./
      dockerfile: ./Dockerfile-test
    container_name: backendTest
    command: python docker_backend_testing.py
#    command: sh -c "/wait" && python docker_backend_testing.py
#    environment:
#      - WAIT_HOSTS=rest_app:5000
#      - WAIT_HOSTS_TIMEOUT=300
#      - WAIT_SLEEP_INTERVAL=30
#      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    depends_on:
      - rest_app
    links:
      - "rest_app"
