version: '3'
services:
  db:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mydb
      - MYSQL_HOST=localhost
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3309:3306"

  rest_app:
    build: .
    container_name: restApp
    command: python rest_app.py
    ports:
      - "5000:5000"
    expose:
      - 5000
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - "db"

  backend_testing_app:
    build: .
    container_name: backendTest
    command: python docker_backend_testing.py
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    depends_on:
      - rest_app
    links:
      - "rest_app"
