version: '3'
services:
  db:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mydb
      - MYSQL_HOST=localhost
    volumes:
      - C:\Users\osame\mysql:/var/lib/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3309:3306"
    expose:
      - 3306

  db_connector:
    build: .
    container_name: dbConnector
    ports:
      - "5002:5002"
    volumes:
      - C:\Users\osame\mysql:/var/lib/mysql
    depends_on:
      - db
    links:
      - "db:mydb"
    command: sh -c "/wait" && python db_connector.py
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  rest_app:
    build: .
    container_name: restApp
    command: python rest_app.py
    ports:
      - "5000:5000"
    expose:
      - 5000
    volumes:
      - .:/app
    depends_on:
      - db_connector
    links:
      - "db_connector"

  backend_testing_app:
    build:
      context: ./
      dockerfile: ./Dockerfile-test
    container_name: backendTest
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    depends_on:
      - rest_app
    links:
      - "rest_app"
    command: sh -c "/wait" && python docker_backend_testing.py
    environment:
      - WAIT_HOSTS=rest_app:5000
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30